"""Wire the memory classifier into a local LLM (Ollama) and compare retrieval modes.

For a real MSC conversation we build a memory bank from the previous sessions and
answer live queries under four conditions:

    no_memory  : the query alone
    store_all  : every past memory dumped into context
    top_k      : the k memories most cosine-similar to the query (the incumbent)
    ml_selected: memories the trained classifier predicts as "retain"

Each answer is generated by ``llama3.1:8b`` and scored by an independent judge
model (``dolphin-mistral``) for how well it uses relevant remembered facts. We
also report the number of context tokens each mode spends -- the efficiency angle.
"""
from __future__ import annotations

import argparse
import json
import re
from pathlib import Path

import pandas as pd
import requests

from scorer import MemoryScorer, episode_memories

ROOT = Path(__file__).resolve().parent.parent
RAW = ROOT / "data" / "raw" / "msc"
RESULTS = ROOT / "results"

OLLAMA = "http://localhost:11434/api/generate"
GEN_MODEL = "llama3.1:8b-instruct-q4_K_M"
JUDGE_MODEL = "dolphin-mistral:latest"

SYSTEM = (
    "You are a helpful assistant in an ongoing relationship with a user across "
    "many conversations. Use the remembered facts about the user when they are "
    "relevant. Keep replies to 2-3 sentences."
)


def generate(prompt: str, model: str = GEN_MODEL, system: str | None = None,
             num_predict: int = 160) -> str:
    payload = {
        "model": model, "prompt": prompt, "stream": False,
        "options": {"temperature": 0, "num_predict": num_predict},
    }
    if system:
        payload["system"] = system
    r = requests.post(OLLAMA, json=payload, timeout=180)
    r.raise_for_status()
    return r.json()["response"].strip()


def build_prompt(query: str, memories: list[str]) -> str:
    if memories:
        block = "\n".join(f"- {m}" for m in memories)
        return f"Things you remember about this user:\n{block}\n\nUser: {query}\nAssistant:"
    return f"User: {query}\nAssistant:"


def _tokens(memories: list[str]) -> int:
    return sum(len(m.split()) for m in memories)


def judge(query: str, response: str) -> int:
    """Independent 1-5 rating of relevance + use of remembered context."""
    prompt = (
        "Rate the assistant reply from 1 to 5 on how relevant, specific, and "
        "personalized it is to the user message (5 = highly relevant and clearly "
        "uses what it knows about the user; 1 = generic or off-topic). "
        "Answer with a single integer only.\n\n"
        f"User: {query}\nAssistant: {response}\n\nRating:"
    )
    out = generate(prompt, model=JUDGE_MODEL, num_predict=4)
    m = re.search(r"[1-5]", out)
    return int(m.group()) if m else 0


def get_demo_episode(session: int = 5, split: str = "valid", index: int = 0):
    path = RAW / "msc_dialogue" / f"session_{session}" / f"{split}.txt"
    with open(path, encoding="utf-8") as fh:
        for i, line in enumerate(fh):
            if i == index:
                rec = json.loads(line)
                break
    memories = episode_memories(rec, rec["previous_dialogs"], session)
    personas = [s for side in (rec.get("personas") or [[], []]) for s in side]
    # queries = Speaker-1 turns; gold = the following Speaker-2 reply
    dialog = rec["dialog"]
    qa = []
    for k in range(len(dialog) - 1):
        if dialog[k].get("id") == "Speaker 1" and dialog[k + 1].get("id") == "Speaker 2":
            qa.append((dialog[k]["text"], dialog[k + 1]["text"]))
    return memories, personas, qa


def compare(scorer: MemoryScorer, memories, personas, query, k=5, threshold=0.5):
    feats = scorer.features(memories, query, personas)
    probs = scorer.pipeline.predict_proba(feats)[:, 1]
    sims = feats["sim_to_current_query"].values
    texts = [m["text"] for m in memories]

    top_k = [texts[i] for i in sims.argsort()[::-1][:k]]
    ml_idx = [i for i in range(len(texts)) if probs[i] >= threshold]
    if not ml_idx:
        ml_idx = list(probs.argsort()[::-1][:3])
    ml_idx = sorted(ml_idx, key=lambda i: -probs[i])[:8]
    ml_sel = [texts[i] for i in ml_idx]

    modes = {
        "no_memory": [],
        "store_all": texts,
        "top_k": top_k,
        "ml_selected": ml_sel,
    }
    rows = []
    for mode, mems in modes.items():
        resp = generate(build_prompt(query, mems), system=SYSTEM)
        rows.append({
            "mode": mode,
            "n_memories": len(mems),
            "context_tokens": _tokens(mems),
            "judge_score": judge(query, resp),
            "response": resp,
        })
    return rows, probs, sims


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--session", type=int, default=5)
    ap.add_argument("--index", type=int, default=0)
    ap.add_argument("--num-episodes", type=int, default=1)
    ap.add_argument("--num-queries", type=int, default=4)
    ap.add_argument("--k", type=int, default=5)
    args = ap.parse_args()

    scorer = MemoryScorer()
    all_rows = []
    for ep in range(args.index, args.index + args.num_episodes):
        memories, personas, qa = get_demo_episode(args.session, index=ep)
        print(f"=== Episode {ep}: {len(memories)} memories, {len(personas)} persona facts, "
              f"{len(qa)} queries. Classifier: {scorer.name}")
        for qi, (query, gold) in enumerate(qa[: args.num_queries]):
            rows, probs, sims = compare(scorer, memories, personas, query, k=args.k)
            for r in rows:
                r["episode"] = ep
                r["query_id"] = qi
                r["query"] = query
                all_rows.append(r)
                print(f"  q{qi} {r['mode']:12s} mems={r['n_memories']:2d} "
                      f"tok={r['context_tokens']:4d} judge={r['judge_score']}  {r['response'][:70]}")
        print()

    df = pd.DataFrame(all_rows)
    RESULTS.mkdir(exist_ok=True)
    df.to_csv(RESULTS / "llm_comparison.csv", index=False)

    summary = df.groupby("mode").agg(
        avg_judge=("judge_score", "mean"),
        avg_context_tokens=("context_tokens", "mean"),
        avg_memories=("n_memories", "mean"),
    ).round(2)
    print("Summary by mode:")
    print(summary.to_string())
    summary.to_csv(RESULTS / "llm_summary.csv")
    with open(RESULTS / "llm_demo.json", "w") as fh:
        json.dump(all_rows, fh, indent=2)
    print(f"\nSaved -> {RESULTS/'llm_comparison.csv'}, {RESULTS/'llm_summary.csv'}")


if __name__ == "__main__":
    main()
